// <auto-generated>
//   Generated by rebuild/tools/gen_settings.py from the PowerShell tool.
//   Do not edit by hand while lib/_common.ps1 still exists - re-run the
//   generator instead, or the two will disagree silently.
// </auto-generated>

#nullable enable

namespace SessionRestore.Core.Config;

/// <summary>Every setting the tool supports, with the ONE default it uses.</summary>
/// <remarks>
/// The PowerShell keeps this in three places - Get-SRConfigRead's table, the
/// settings screen's $SR_CfgMeta, and inline at the point of use. Where two of
/// them define the same key they agree (checked 2026-09-09), so collapsing them
/// loses nothing; leaving them apart is what eventually makes them differ.
/// </remarks>
public static class SettingsCatalog
{
    /// <summary>The settings, in key order.</summary>
    public static IReadOnlyList<SettingDef> All { get; } =
    [
        new SettingDef(
            Key: "autoTickLaneBudgets",
            Group: "What comes back at your next logon",
            Label: "Per-project auto-tick budgets",
            Help: "Set these from the \"auto on / auto off\" control on a project tile rather than by hand. 0 means never auto-tick that lane; the longest matching pattern wins.",
            Kind: SettingKind.Map,
            Default: null,
            Min: null,
            Max: null,
            Options: null),
        new SettingDef(
            Key: "autoTickPerDirectory",
            Group: "What comes back at your next logon",
            Label: "Most conversations auto-ticked per project",
            Help: "The hourly roll arms at most this many newly seen conversations in one project, newest first - so a repo with sixteen live conversations does not open sixteen tabs.",
            Kind: SettingKind.Number,
            Default: 3,
            Min: 1,
            Max: 1000,
            Options: null),
        new SettingDef(
            Key: "autoTickPerWorktree",
            Group: "What comes back at your next logon",
            Label: "Most conversations auto-ticked per worktree",
            Help: "The same cap again, applied to each worktree separately, because a worktree is its own lane of work.",
            Kind: SettingKind.Number,
            Default: 3,
            Min: 1,
            Max: 1000,
            Options: null),
        new SettingDef(
            Key: "excludePatterns",
            Group: "Where it looks for conversations",
            Label: "Folders never scanned for conversations",
            Help: "Wildcard paths. A conversation under one of these is never recorded at all, so this erases history rather than hiding it - unlike shelving a project.",
            Kind: SettingKind.List,
            Default: null,
            Min: null,
            Max: null,
            Options: null),
        new SettingDef(
            Key: "foldProjects",
            Group: "What the lists show",
            Label: "Start with the projects column collapsed",
            Help: "The window writes this back for you whenever you collapse or open that column.",
            Kind: SettingKind.Text,
            Default: null,
            Min: null,
            Max: null,
            Options: null),
        new SettingDef(
            Key: "foldSessions",
            Group: "What the lists show",
            Label: "Start with the conversations column collapsed",
            Help: "The window writes this back for you whenever you collapse or open that column.",
            Kind: SettingKind.Text,
            Default: null,
            Min: null,
            Max: null,
            Options: null),
        new SettingDef(
            Key: "includeWorktrees",
            Group: "What comes back at your next logon",
            Label: "Reopen conversations from git worktrees",
            Help: "Off also silences worktree conversations already recorded, so nothing you switched off comes back the next morning.",
            Kind: SettingKind.Toggle,
            Default: true,
            Min: null,
            Max: null,
            Options: null),
        new SettingDef(
            Key: "launchGapMs",
            Group: "What comes back at your next logon",
            Label: "Pause between opening one tab and the next",
            Help: "Milliseconds. The gap stops Windows Terminal racing itself, and the failure it prevents is a tab that opens and dies. 250 is the tuned value; 0 means no pause at all.",
            Kind: SettingKind.Number,
            Default: 250,
            Min: 0,
            Max: 2000,
            Options: null),
        new SettingDef(
            Key: "lineSpacing",
            Group: "The reading pane",
            Label: "How far apart the lines of a reply sit",
            Help: "Your terminal draws lines 1,16 times the font size apart. Normal is 1,45 here, because a proportional face needs more than a terminal one.",
            Kind: SettingKind.Choice,
            Default: "normal",
            Min: null,
            Max: null,
            Options: ["tight", "normal", "relaxed"]),
        new SettingDef(
            Key: "listDays",
            Group: "What the lists show",
            Label: "Days of conversations in the list",
            Help: "Nothing older is hidden silently: what falls outside is counted on a row at the end, and a search still reaches past it.",
            Kind: SettingKind.Number,
            Default: 7,
            Min: 1,
            Max: 3650,
            Options: null),
        new SettingDef(
            Key: "maxSessions",
            Group: "What comes back at your next logon",
            Label: "Most conversations to reopen at once",
            Help: "A logon restore stops at this many. Anything ticked beyond it stays ticked and simply waits for the next time.",
            Kind: SettingKind.Number,
            Default: 12,
            Min: 1,
            Max: 1000,
            Options: null),
        new SettingDef(
            Key: "oauthTokenUrl",
            Group: "Other settings in this file",
            Label: "Sign-in token endpoint",
            Help: "Only set this if the built-in endpoint is wrong for this machine. Empty means use the built-in one.",
            Kind: SettingKind.Text,
            Default: null,
            Min: null,
            Max: null,
            Options: null),
        new SettingDef(
            Key: "panelScanMaxAgeSeconds",
            Group: "Other settings in this file",
            Label: "Panel scan freshness (no longer read)",
            Help: "Nothing in this tool reads this any more - it belonged to an opening scan that has since been removed. It is left in the file so an older copy still finds what it expects.",
            Kind: SettingKind.Number,
            Default: null,
            Min: 0,
            Max: 86400,
            Options: null),
        new SettingDef(
            Key: "railBandsShut",
            Group: "What the lists show",
            Label: "Age bands folded shut in the projects rail",
            Help: "Which headings start closed. The rail folds these as you click them too; this is only where it starts.",
            Kind: SettingKind.Flags,
            Default: "week,month,older",
            Min: null,
            Max: null,
            Options: ["today", "week", "month", "older"]),
        new SettingDef(
            Key: "readingWidth",
            Group: "The reading pane",
            Label: "How wide a line of text runs",
            Help: "Measured keeps a line short enough to read comfortably; full uses the whole pane.",
            Kind: SettingKind.Choice,
            Default: "full",
            Min: null,
            Max: null,
            Options: ["full", "measured"]),
        new SettingDef(
            Key: "recencyDays",
            Group: "What comes back at your next logon",
            Label: "Days a project counts as recently worked in",
            Help: "A project first seen inside this window arrives ticked. Older ones are recorded but left alone.",
            Kind: SettingKind.Number,
            Default: 14,
            Min: 1,
            Max: 3650,
            Options: null),
        new SettingDef(
            Key: "registryWindowDays",
            Group: "What the lists show",
            Label: "Days a conversation stays tracked at all",
            Help: "This bounds what is recorded, not just what is shown. Past it, a conversation drops out of the registry entirely.",
            Kind: SettingKind.Number,
            Default: 30,
            Min: 1,
            Max: 3650,
            Options: null),
        new SettingDef(
            Key: "sessionWindowDays",
            Group: "What comes back at your next logon",
            Label: "Days a conversation counts as recently active",
            Help: "A newly seen conversation is auto-ticked only if it was active inside this window - and then only up to the caps above.",
            Kind: SettingKind.Number,
            Default: 3,
            Min: 1,
            Max: 3650,
            Options: null),
        new SettingDef(
            Key: "shelveSuggestDays",
            Group: "What the lists show",
            Label: "Quiet days before a project is suggested for shelving",
            Help: "A sentence on the tile and nothing more - nothing is ever shelved on its own.",
            Kind: SettingKind.Number,
            Default: 14,
            Min: 1,
            Max: 3650,
            Options: null),
        new SettingDef(
            Key: "terminalColour",
            Group: "The reading pane",
            Label: "Colour when you watch a session",
            Help: "A sixteen-colour approximation, which is all the console buffer keeps - claude paints in 24-bit and what comes back is what Windows rounded that to. It costs a second screen read and a redraw of the panel per frame, so turn it off if you are watching something very busy.",
            Kind: SettingKind.Choice,
            Default: "on",
            Min: null,
            Max: null,
            Options: ["on", "off"]),
        new SettingDef(
            Key: "textRendering",
            Group: "How it looks",
            Label: "How text is rasterised",
            Help: "ClearType is sharper on an ordinary monitor; grayscale is what the type was drawn for and is even at any size.",
            Kind: SettingKind.Choice,
            Default: "grayscale",
            Min: null,
            Max: null,
            Options: ["grayscale", "cleartype"]),
        new SettingDef(
            Key: "transcriptTools",
            Group: "The reading pane",
            Label: "How much of the machinery the transcript shows",
            Help: "Measured across six transcripts, tool traffic outnumbers prose five to one - that ratio is the wall of text.",
            Kind: SettingKind.Choice,
            Default: "folded",
            Min: null,
            Max: null,
            Options: ["folded", "full", "hidden"]),
        new SettingDef(
            Key: "yourGround",
            Group: "The reading pane",
            Label: "The background behind your own messages",
            Help: "A surface behind your words, so they read as yours at a glance down a long conversation. Drawn as a light tint of the colour, never the colour itself - a solid ground behind body text is a highlighter pen.",
            Kind: SettingKind.Choice,
            Default: "neutral",
            Min: null,
            Max: null,
            Options: ["neutral", "orange", "blue", "violet", "none"]),
        new SettingDef(
            Key: "yourInk",
            Group: "The reading pane",
            Label: "The colour of your own messages",
            Help: "Set this and leave the background at none for the quieter treatment: coloured text, nothing behind it.",
            Kind: SettingKind.Choice,
            Default: "normal",
            Min: null,
            Max: null,
            Options: ["normal", "orange", "blue", "violet"]),
        new SettingDef(
            Key: "zoom",
            Group: "How it looks",
            Label: "Size of everything on the surface, as a percentage",
            Help: "One number for the whole window. Below 70 the smallest step stops resolving; above 200 a maximised window fits less than a phone.",
            Kind: SettingKind.Number,
            Default: 100,
            Min: 70,
            Max: 200,
            Options: null),
    ];

    private static readonly Dictionary<string, SettingDef> ByKeyMap =
        All.ToDictionary(s => s.Key, StringComparer.Ordinal);

    /// <summary>The definition for one key, or null if the tool has no such setting.</summary>
    /// <remarks>Ordinal: a settings key is an identifier, never prose, and a
    /// culture-sensitive compare on one of those is how this repo lost a day.</remarks>
    public static SettingDef? Find(string key) =>
        ByKeyMap.TryGetValue(key, out var d) ? d : null;
}
