# Extract the marked knowledge out of the PowerShell sources.
#
# WHY THIS IS A SCRIPT AND NOT A DOCUMENT SOMEBODY WROTE. The rebuild's whole
# risk is that a fact which took days to establish gets re-derived wrongly in
# the new language. Those facts are already written down - beside the code they
# constrain, marked with one of six glyphs - and there are over a thousand of
# them. A human summary of a thousand facts is a lossy summary of a thousand
# facts. This copies them VERBATIM, with the file and line they came from, and
# can be re-run when the PowerShell moves.
#
#   RED    a defect that was reported, or a rule that must not be broken
#   TRAP   a thing that looks right and is not
#   KEY    the load-bearing insight of a design
#   LOCK   a safety boundary
#   HOOK   a test seam / an A-B control kept reachable on purpose
#   PLANT  a deliberate, documented behaviour choice
#
# Usage:  python rebuild/tools/extract_knowledge.py
# Writes: rebuild/02-KNOWLEDGE.md  (and a JSON sidecar for other tools)
import io, os, json, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'rebuild')

MARKS = [
    ('RED',   0x1F534), ('TRAP',  0x1FAA4), ('KEY',   0x1F511),
    ('LOCK',  0x1F512), ('HOOK',  0x1FA9D), ('PLANT', 0x1FAB4),
]
GLYPH = dict((chr(c), n) for n, c in MARKS)

SOURCES = [
    ('lib/sessions-window.ps1', 'the window'),
    ('lib/_common.ps1',         'the domain'),
    ('app/SessionsHost.cs',     'the host'),
]


def blocks(lines, comment_prefix):
    """Contiguous runs of comment lines, as (start_index, end_index) inclusive."""
    out = []
    i = 0
    n = len(lines)
    while i < n:
        if lines[i].strip().startswith(comment_prefix):
            j = i
            while j + 1 < n and lines[j + 1].strip().startswith(comment_prefix):
                j += 1
            out.append((i, j))
            i = j + 1
        else:
            i += 1
    return out


def enclosing(lines, idx, pat):
    """Nearest preceding definition name, so a fact can be filed under what it constrains."""
    for k in range(idx, -1, -1):
        m = pat.match(lines[k])
        if m:
            return m.group(1)
    return '(file scope)'


def anchor(lines, end):
    """The first line of actual code the block sits on top of."""
    for k in range(end + 1, min(end + 8, len(lines))):
        t = lines[k].strip()
        if t and not t.startswith('#') and not t.startswith('//'):
            return t[:120]
    return ''


def harvest():
    found = []
    for rel, area in SOURCES:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            sys.stderr.write('missing: %s\n' % rel)
            continue
        text = io.open(path, encoding='utf-8').read()
        lines = text.split('\n')
        if rel.endswith('.cs'):
            prefix = '//'
            pat = re.compile(r'^\s*(?:public|private|internal|protected|static).*?\s([A-Za-z_]\w*)\s*\(')
        else:
            prefix = '#'
            pat = re.compile(r'^\s*function\s+([A-Za-z][\w\-]*)')
        for (a, b) in blocks(lines, prefix):
            body = lines[a:b + 1]
            joined = '\n'.join(body)
            kinds = sorted(set(GLYPH[g] for g in GLYPH if g in joined))
            if not kinds:
                continue
            stripped = []
            for l in body:
                t = l.strip()
                t = t[len(prefix):] if t.startswith(prefix) else t
                stripped.append(t.rstrip())
            while stripped and not stripped[0].strip('- '):
                stripped.pop(0)
            while stripped and not stripped[-1].strip('- '):
                stripped.pop()
            found.append({
                'file': rel,
                'area': area,
                'line': a + 1,
                'kinds': kinds,
                'under': enclosing(lines, a, pat),
                'anchor': anchor(lines, b),
                'text': '\n'.join(stripped),
            })
    return found


def main():
    if not os.path.isdir(OUT):
        os.makedirs(OUT)
    found = harvest()

    counts = {}
    for f in found:
        for k in f['kinds']:
            counts[k] = counts.get(k, 0) + 1

    # Grouped by the thing the fact constrains, so the rebuild can work through
    # one subsystem at a time instead of reading a thousand notes in file order.
    by_area = {}
    for f in found:
        by_area.setdefault(f['area'], {}).setdefault(f['under'], []).append(f)

    md = []
    md.append('# The knowledge ledger')
    md.append('')
    md.append('**Generated by `rebuild/tools/extract_knowledge.py` - do not edit by hand.**')
    md.append('Re-run it whenever the PowerShell moves.')
    md.append('')
    md.append('Every one of these was written beside the code it constrains, and almost')
    md.append('all of them were written after something was wrong. They are copied here')
    md.append('verbatim because the rebuild\'s central risk is re-deriving one of them')
    md.append('incorrectly in a new language.')
    md.append('')
    md.append('| marker | meaning | count |')
    md.append('|---|---|---|')
    order = ['RED', 'TRAP', 'KEY', 'LOCK', 'HOOK', 'PLANT']
    meaning = {
        'RED': 'a reported defect, or a rule that must not be broken',
        'TRAP': 'a thing that looks right and is not',
        'KEY': 'the load-bearing insight of a design',
        'LOCK': 'a safety boundary',
        'HOOK': 'a test seam or an A/B control kept reachable on purpose',
        'PLANT': 'a deliberate, documented behaviour choice',
    }
    for k in order:
        md.append('| %s | %s | %d |' % (k, meaning[k], counts.get(k, 0)))
    md.append('| | **blocks in total** | **%d** |' % len(found))
    md.append('')

    for area in ['the domain', 'the window', 'the host']:
        if area not in by_area:
            continue
        md.append('')
        md.append('---')
        md.append('')
        md.append('# %s' % area.upper())
        md.append('')
        groups = by_area[area]
        for under in sorted(groups.keys(), key=lambda s: (s == '(file scope)', s.lower())):
            items = groups[under]
            md.append('## `%s`' % under)
            md.append('')
            for f in items:
                md.append('### %s &mdash; `%s:%d`' % ('/'.join(f['kinds']), f['file'], f['line']))
                md.append('')
                md.append('```text')
                md.append(f['text'])
                md.append('```')
                if f['anchor']:
                    md.append('')
                    md.append('sits on: `%s`' % f['anchor'])
                md.append('')

    io.open(os.path.join(OUT, '02-KNOWLEDGE.md'), 'w', encoding='utf-8').write('\n'.join(md))
    io.open(os.path.join(OUT, 'knowledge.json'), 'w', encoding='utf-8').write(
        json.dumps(found, indent=1, ensure_ascii=False))

    print('%d marked blocks' % len(found))
    for k in order:
        print('  %-6s %d' % (k, counts.get(k, 0)))
    print('-> rebuild/02-KNOWLEDGE.md')


if __name__ == '__main__':
    main()
