# Extract the BEHAVIOUR SPEC out of the test suites.
#
# WHY THE TESTS ARE THE SPEC. gui2-driver.ps1 says of itself: "Every assertion
# here was written against a real defect found while building the thing it
# covers - none of them are decorative." That makes the assertion messages the
# only complete, non-aspirational statement of what this tool is supposed to do.
# There are thousands of them and no human is going to re-read them all in the
# new language, so they are pulled out here as a checklist to work through.
#
# 30,000 lines of PowerShell harness will NOT survive the rebuild. These
# sentences are what has to.
#
# Usage:  python rebuild/tools/extract_behaviour.py
# Writes: rebuild/04-BEHAVIOUR.md, rebuild/behaviour.json
import io, os, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'rebuild')
TESTS = os.path.join(ROOT, 'tests')

# The suites that assert about the SHIPPED window and the domain. The retired
# window's drivers are deliberately excluded: gui2-driver says their green says
# nothing about the app, and carrying their assertions into the rebuild would
# import requirements for a window that no longer exists.
RETIRED = ('headless', 'inbox-driver', 'keys-driver', 'app-driver')

SECTION = re.compile(r"^\s*Write-Host\s+'---\s*(.+?)\s*---'")

# 🪤 THE ASSERTION IS USUALLY NOT AT THE START OF ITS LINE. The idiom in these
# suites is `if (bad) { Fail '...' } else { Pass '...' }` all on one line, and
# 501 of gui2's 900 are written that way - an anchored regex found 742 of 2,412
# and looked like it had done the job. So the call is found ANYWHERE on the
# line, and the string after it is read by hand rather than matched, because
# `Pass ('{0} of {1}' -f $a, $b)` puts a paren and a format tail around it.
CALL = re.compile(r"(?<![\w-])(Pass|Fail|ZsPass|ZsFail|ZrPass)\s*\(?\s*(['\"])")


def read_string(s, i, q):
    """From the opening quote at i, the literal's content. Doubling escapes a
    quote in PowerShell ('' inside '...'); backtick escapes inside "..."."""
    out = []
    i += 1
    n = len(s)
    while i < n:
        c = s[i]
        if c == '`' and q == '"' and i + 1 < n:
            out.append(s[i + 1]); i += 2; continue
        if c == q:
            if i + 1 < n and s[i + 1] == q:
                out.append(q); i += 2; continue
            return ''.join(out), i + 1
        out.append(c)
        i += 1
    return ''.join(out), n


def tidy(s):
    s = s.strip()
    s = re.sub(r'\{\d+(?::[^}]*)?\}', '<n>', s)          # -f placeholders
    s = re.sub(r'\$\([^)]*\)|\$\w+(?:\.\w+)*', '<v>', s)  # interpolated values
    s = re.sub(r'\s+', ' ', s)
    return s


def harvest():
    out = []
    for fn in sorted(os.listdir(TESTS)):
        if not fn.endswith('.ps1'):
            continue
        if any(r in fn for r in RETIRED):
            continue
        path = os.path.join(TESTS, fn)
        lines = io.open(path, encoding='utf-8', errors='replace').read().split('\n')
        section = '(no section)'
        seen = set()
        for i, l in enumerate(lines):
            m = SECTION.match(l)
            if m:
                section = m.group(1)
                continue
            if l.strip().startswith('#'):
                continue
            for a in CALL.finditer(l):
                txt, _ = read_string(l, a.end(2) - 1, a.group(2))
                t = tidy(txt)
                if len(t) < 8:
                    continue
                kind = 'rejects' if 'Fail' in a.group(1) else 'requires'
                key = (kind, t)
                if key in seen:
                    continue
                seen.add(key)
                out.append({'suite': fn, 'section': section,
                            'line': i + 1, 'kind': kind, 'text': t})
    return out


def main():
    found = harvest()
    # A behaviour is stated twice - once as the green sentence and once as the
    # red one - so the two are shown together per section rather than as two
    # unrelated lists.
    by_suite = {}
    for f in found:
        by_suite.setdefault(f['suite'], {}).setdefault(f['section'], []).append(f)

    md = []
    md.append('# The behaviour spec')
    md.append('')
    md.append('**Generated by `rebuild/tools/extract_behaviour.py` - do not edit by hand.**')
    md.append('')
    md.append('Every assertion in the suites that cover the SHIPPED window and the domain.')
    md.append('gui2-driver says of itself that every one of its assertions was written')
    md.append('against a real defect and none are decorative - which makes these sentences')
    md.append('the only complete statement of what this tool is supposed to do.')
    md.append('')
    md.append('**The 30,000 lines of PowerShell harness will not survive the rebuild.**')
    md.append('These sentences have to. Work through them as a checklist; each one is a')
    md.append('test to write in the new language, and the line reference is where to read')
    md.append('what it actually checked.')
    md.append('')
    md.append('- **%d** assertions across **%d** suites' % (len(found), len(by_suite)))
    md.append('- `requires` is what the tool must do; `rejects` is what it must not')
    md.append('')
    md.append('| suite | assertions |')
    md.append('|---|---|')
    for s in sorted(by_suite, key=lambda k: -sum(len(v) for v in by_suite[k].values())):
        md.append('| `tests/%s` | %d |' % (s, sum(len(v) for v in by_suite[s].values())))
    md.append('')

    for suite in sorted(by_suite, key=lambda k: -sum(len(v) for v in by_suite[k].values())):
        md.append('')
        md.append('---')
        md.append('')
        md.append('## `tests/%s`' % suite)
        md.append('')
        for section in by_suite[suite]:
            items = by_suite[suite][section]
            md.append('### %s' % section)
            md.append('')
            for it in items:
                mark = '- [ ] ' if it['kind'] == 'requires' else '- [ ] MUST NOT: '
                md.append('%s%s  <sub>`%s:%d`</sub>' % (mark, it['text'], suite, it['line']))
            md.append('')

    io.open(os.path.join(OUT, '04-BEHAVIOUR.md'), 'w', encoding='utf-8').write('\n'.join(md))
    io.open(os.path.join(OUT, 'behaviour.json'), 'w', encoding='utf-8').write(
        json.dumps(found, indent=1, ensure_ascii=False))
    print('%d assertions across %d suites' % (len(found), len(by_suite)))
    print('-> rebuild/04-BEHAVIOUR.md')


if __name__ == '__main__':
    main()
