using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace SessionRestore.Core.Transcripts;

/// <summary>One message waiting behind the turn a conversation is on.</summary>
/// <param name="Text">What was queued, ANSI removed, hop-chain kept.</param>
/// <param name="First">Its first meaningful line.</param>
/// <param name="At">When it was queued, in local time; null when the record did not say.</param>
/// <param name="Mine">Typed by a person rather than generated by the machine.</param>
public sealed record QueuedMessage(string Text, string First, DateTime? At, bool Mine);

/// <summary>What is queued in one conversation.</summary>
/// <param name="LastWrite">The transcript's write time, local. 🪤 MinValue means NOT KNOWN, never "infinitely stale".</param>
public sealed record QueueState(IReadOnlyList<QueuedMessage> Items, int Mine, int Machine, bool Ok, DateTime LastWrite)
{
    public int Count => Items.Count;

    public static QueueState None { get; } = new([], 0, 0, false, DateTime.MinValue);
}

/// <summary>
/// The queue a conversation has built up, replayed from its transcript's own
/// queue-operation records. Ported from <c>Get-SRQueue</c> and
/// <c>Test-SRQueueFresh</c>.
/// </summary>
/// <remarks>
/// 🔴 CASE-INSENSITIVE WHERE THE POWERSHELL IS, which is three places that do
/// not look like comparisons: <c>-ne 'queue-operation'</c>, a <c>switch</c> on
/// the operation name, and <c>-eq</c> matching a remove to its enqueue. Each is
/// ported as OrdinalIgnoreCase rather than tidied into Ordinal.
/// </remarks>
public static class Waiting
{
    /// <summary><c>$SR_QueueTailBytes</c>.</summary>
    public const int TailBytes = 4194304;

    /// <summary><c>$SR_QueueStaleHours</c>: how long one of YOUR messages stays current.</summary>
    public const double StaleHours = 1.0;

    /// <summary><c>$SR_QueueMachineStaleMins</c>: machine traffic is eaten on the next turn.</summary>
    public const double MachineStaleMinutes = 2.0;

    private static readonly Regex HopChain = new(@"\s+hop-chain=""[^""]*""", RegexOptions.CultureInvariant);

    /// <summary>
    /// The text a remove is matched on.
    /// </summary>
    /// <remarks>
    /// 🔴 THE ENQUEUE AND THE REMOVE OF ONE MESSAGE ARE NOT THE SAME STRING: a
    /// cross-session enqueue carries <c>hop-chain="..."</c> on its opening tag and
    /// its remove does not. Matching the raw text left 37 messages queued forever
    /// on one transcript. The key is for MATCHING only - the text keeps it.
    /// </remarks>
    public static string Key(string? text) =>
        string.IsNullOrEmpty(text) ? string.Empty : HopChain.Replace(text, string.Empty);

    /// <summary>Replays the queue records in the last <paramref name="maxTailBytes"/> of a transcript.</summary>
    public static QueueState Read(string? jsonlPath, int maxTailBytes = 0)
    {
        if (maxTailBytes <= 0)
        {
            maxTailBytes = TailBytes;
        }

        if (string.IsNullOrEmpty(jsonlPath) || !File.Exists(jsonlPath))
        {
            return QueueState.None;
        }

        FileInfo fi;
        try
        {
            fi = new FileInfo(jsonlPath);
            _ = fi.Length;
        }
        catch (IOException)
        {
            return QueueState.None;
        }

        if (fi.Length == 0)
        {
            return QueueState.None;
        }

        string text;
        try
        {
            using var fs = new FileStream(jsonlPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
            var take = (int)Math.Min(fi.Length, maxTailBytes);
            fs.Seek(-take, SeekOrigin.End);
            var buf = new byte[take];

            // 🪤 ONE Read, as the PowerShell does. A loop that fills the buffer
            // would read MORE than the original on the rare short read, and the
            // two would disagree about the one record at the boundary.
            var read = fs.Read(buf, 0, take);
            text = Encoding.UTF8.GetString(buf, 0, read);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return QueueState.None;
        }

        var q = new List<(string Text, DateTime? At, string Key)>();
        foreach (var ln in text.Split('\n'))
        {
            if (ln.IndexOf("\"queue-operation\"", StringComparison.Ordinal) < 0)
            {
                continue;
            }

            var s = ln.TrimStart('\uFEFF', ' ', '\t');
            if (!s.StartsWith('{'))
            {
                continue;
            }

            JsonDocument doc;
            try
            {
                doc = JsonDocument.Parse(s);
            }
            catch (JsonException)
            {
                continue;
            }

            using (doc)
            {
                if (doc.RootElement.ValueKind != JsonValueKind.Object)
                {
                    continue;
                }

                if (!string.Equals(Str(doc.RootElement, "type"), "queue-operation", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                var op = Str(doc.RootElement, "operation");
                var c = Str(doc.RootElement, "content");
                if (string.Equals(op, "enqueue", StringComparison.OrdinalIgnoreCase))
                {
                    if (c.Trim().Length == 0)
                    {
                        continue;
                    }

                    var clean = TranscriptText.RemoveAnsi(c);
                    q.Add((clean, When(doc.RootElement), Key(clean)));
                }
                else if (string.Equals(op, "popAll", StringComparison.OrdinalIgnoreCase))
                {
                    q.Clear();
                }
                else if (string.Equals(op, "remove", StringComparison.OrdinalIgnoreCase))
                {
                    // 🪤 A REMOVE THAT MATCHES NOTHING IS IGNORED, not treated as
                    // popping the front - right for a truncated window, where it
                    // under-reports instead of dropping somebody's message.
                    var rk = Key(TranscriptText.RemoveAnsi(c));
                    var at = q.FindIndex(e => string.Equals(e.Key, rk, StringComparison.OrdinalIgnoreCase));
                    if (at >= 0)
                    {
                        q.RemoveAt(at);
                    }
                }
                else if (string.Equals(op, "dequeue", StringComparison.OrdinalIgnoreCase) && q.Count > 0)
                {
                    q.RemoveAt(0);
                }
            }
        }

        var items = new List<QueuedMessage>(q.Count);
        int mine = 0, machine = 0;
        foreach (var e in q)
        {
            // Every machine-generated prompt arrives wrapped in a tag; a person's
            // message never starts with one.
            var isMine = !e.Text.TrimStart().StartsWith('<');
            if (isMine)
            {
                mine++;
            }
            else
            {
                machine++;
            }

            items.Add(new QueuedMessage(e.Text, LastSaid.FirstLine(e.Text), e.At, isMine));
        }

        DateTime lastWrite;
        try
        {
            lastWrite = fi.LastWriteTime;
        }
        catch (IOException)
        {
            lastWrite = DateTime.MinValue;
        }

        return new QueueState(items, mine, machine, true, lastWrite);
    }

    /// <summary>
    /// Is anything in this queue still current?
    /// </summary>
    /// <remarks>
    /// 🔴 IT ONLY EVER HIDES A MARK, SO IT FIRES ON EVIDENCE OF AGE AND NEVER ON
    /// THE ABSENCE OF EVIDENCE. No dated item at all means "could not tell", and
    /// that still draws. Claude Code does not always write the record that
    /// cancels an enqueue, so four of six marks on this machine were orphans up
    /// to 136 hours old - which is what this exists for.
    /// </remarks>
    /// <param name="machineMinutes">When positive, an item that is not yours goes stale after this many minutes instead.</param>
    public static bool Fresh(QueueState? rec, DateTime now, double maxHours, double machineMinutes = 0)
    {
        if (rec is null)
        {
            return true;
        }

        int dated = 0, young = 0;
        foreach (var qi in rec.Items)
        {
            if (qi.At is not { } at)
            {
                continue;
            }

            dated++;
            var limit = machineMinutes > 0 && !qi.Mine ? machineMinutes / 60.0 : maxHours;
            if ((now - at).TotalHours <= limit)
            {
                young++;
            }
        }

        return dated <= 0 || young > 0;
    }

    /// <summary>
    /// A string property, looked up the way PowerShell reads a member: case-insensitively,
    /// and stringified the way <c>"$(...)"</c> would.
    /// </summary>
    private static string Str(JsonElement o, string name)
    {
        foreach (var p in o.EnumerateObject())
        {
            if (string.Equals(p.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                return p.Value.ValueKind switch
                {
                    JsonValueKind.String => p.Value.GetString() ?? string.Empty,
                    JsonValueKind.Null or JsonValueKind.Undefined => string.Empty,
                    _ => p.Value.GetRawText(),
                };
            }
        }

        return string.Empty;
    }

    /// <summary><c>[datetime]$r.timestamp</c>: invariant parse, local time, null when it will not parse.</summary>
    private static DateTime? When(JsonElement o)
    {
        var s = Str(o, "timestamp");
        return s.Length > 0 && DateTime.TryParse(s, CultureInfo.InvariantCulture, DateTimeStyles.None, out var d)
            ? d
            : null;
    }
}
