using System.Globalization;
using System.Text;

namespace SessionRestore.Core.Launch;

/// <summary>
/// The little script a conversation is opened with. Plan item 2.5c, and it is a
/// VALUE - there is deliberately no method here that writes one.
/// </summary>
/// <remarks>
/// 🔴 NOTHING IN THIS CLASS TOUCHES THE DISK, AND THAT IS THE GUARD. A boot
/// script is the loaded half of a launch: the moment one exists on disk the only
/// remaining step is handing its path to wt.exe. While the rebuild has no
/// launcher, the safest possible writer is no writer at all - so the text and
/// the path are computed, compared against the PowerShell, and go nowhere.
///
/// 🪤 THE BOOT PATH IS DETERMINISTIC, so anything that freezes that ONE path
/// takes a conversation out of every future restore, silently, forever. On
/// 2026-08-23 an antivirus quarantine did exactly that to
/// boot-MM-toolbox-444f91ed.ps1: that name became unwritable while every other
/// name in the same folder stayed fine. The PowerShell's answer is to fall back
/// to a "-b" name rather than lose the session; that fallback belongs with the
/// writer, and is recorded here so it is not lost when the writer is built.
/// </remarks>
public static class BootScript
{
    /// <summary>
    /// The environment the child must NOT inherit. Without this scrub claude
    /// writes no transcript at all and the conversation cannot be resumed
    /// afterwards - a session that looks fine until you try to come back to it.
    /// </summary>
    public static readonly string[] ChildVars =
    [
        "CLAUDE_CODE_CHILD_SESSION", "CLAUDE_CODE_SESSION_ID", "CLAUDECODE",
        "CLAUDE_CODE_ENTRYPOINT", "CLAUDE_PID", "CLAUDE_CODE_SSE_PORT",
    ];

    // 🔴 PURE ASCII, AND THAT IS A RULE ABOUT OUTPUT RATHER THAN TASTE. This
    // template is written to a .ps1 by a PowerShell 5.1 that reads its own source
    // as ANSI, so a marker emoji in it came back out as nine bytes of mojibake in
    // the operator's boot script. The byte-for-byte oracle case found it as a
    // five-byte length difference; the PowerShell was fixed to match, not this.
    //
    // 🪤 LF, EXPLICITLY, AND NOT WHATEVER THIS FILE HAPPENS TO BE STORED WITH.
    // The PowerShell's here-string carries lib/_common.ps1's own line endings,
    // which are LF; a C# raw string literal would carry this file's, which a
    // checkout or an editor can change without anybody noticing. Joining an
    // array pins it.
    private static readonly string[] Template =
    [
        "# Generated by session-restore -- safe to delete.",
        "# Scrub the inherited child-session environment. Without this, claude writes no",
        "# transcript at all and the conversation cannot be resumed afterwards.",
        "foreach ($v in @(__SCRUBVARS__)) {",
        "    if (Test-Path \"Env:$v\") { Remove-Item \"Env:$v\" -ErrorAction SilentlyContinue }",
        "}",
        "Set-Location -LiteralPath '__DIR__'",
        "# !! THE NAME HAS TO SURVIVE A RE-REGISTRATION, NOT JUST THE LAUNCH.",
        "#",
        "# --remote-control <name> names THIS remote registration and nothing else. Sign in",
        "# to a different account, or drop and re-enable Remote Control by hand, and that",
        "# registration is replaced by one claude names ITSELF -- from",
        "# --remote-control-session-name-prefix, which defaults to the HOSTNAME. Every",
        "# session on the machine then shows up under the same prefix, which is how the",
        "# operator ended up with twenty remote sessions and no way to tell them apart.",
        "#",
        "# Setting the prefix to this conversation's own title fixes the fallback rather",
        "# than the launch: the explicit --remote-control below still wins while it lasts,",
        "# and if it is ever replaced the auto-generated name starts with the title instead",
        "# of the hostname. Purely additive -- it is only ever read when there is no",
        "# explicit name to use.",
        "$env:CLAUDE_REMOTE_CONTROL_SESSION_NAME_PREFIX = '__TITLE__'",
        "# -n writes a DURABLE custom-title into the conversation (precedence rule 2);",
        "# --remote-control names only THIS remote session (rule 1). Both are needed.",
        "__CLAUDELINE__",
    ];

    /// <summary>
    /// Where this conversation's boot script goes.
    /// </summary>
    /// <remarks>
    /// 🔑 THE SESSION ID IS PART OF THE FILENAME. Keying on the directory alone
    /// was fine while only one conversation per tree could be restored; with
    /// several it had them overwrite each other's boot script mid-launch.
    /// </remarks>
    /// <param name="sessionId">Null or empty boots a NEW conversation, which has
    /// no id yet - so the clock keeps two rapid-fire spawns in one directory
    /// apart instead.</param>
    public static string PathFor(string dir, string? sessionId, DateTime? now = null)
    {
        ArgumentNullException.ThrowIfNull(dir);
        var slug = Slug(Leaf(dir));
        if (!string.IsNullOrEmpty(sessionId))
        {
            return Path.Combine(ToolPaths.State,
                string.Create(CultureInfo.InvariantCulture, $"boot-{slug}-{sessionId[..8]}.ps1"));
        }

        var t = (now ?? DateTime.Now).ToString("MMdd-HHmmss-fff", CultureInfo.InvariantCulture);
        return Path.Combine(ToolPaths.State, "boot-new-" + slug + "-" + t + ".ps1");
    }

    /// <summary>
    /// The script's text, LF-terminated lines, exactly as the PowerShell builds
    /// it.
    /// </summary>
    /// <remarks>
    /// 🔴 EVERY VALUE STAYS INSIDE A POWERSHELL SINGLE-QUOTED LITERAL. The
    /// template is substituted rather than interpolated for exactly this reason:
    /// a conversation titled with a <c>$</c> or a backtick must never be re-parsed
    /// as PowerShell in the script that opens it. A name must not cross a shell
    /// boundary as syntax.
    /// </remarks>
    /// <param name="remoteControl">Off means the flag is not passed AT ALL, which
    /// is a different thing from passing it with an empty name.</param>
    public static string Text(
        string dir,
        string? sessionId,
        string title,
        IEnumerable<string>? claudeArgs = null,
        bool remoteControl = true)
    {
        ArgumentNullException.ThrowIfNull(dir);
        ArgumentNullException.ThrowIfNull(title);

        var parts = new List<string> { "& claude" };
        if (!string.IsNullOrEmpty(sessionId))
        {
            parts.Add("--resume");
            parts.Add(Q(sessionId));
        }

        parts.Add("-n");
        parts.Add(Q(title));
        if (remoteControl)
        {
            parts.Add("--remote-control");
            parts.Add(Q(title));
        }

        foreach (var a in claudeArgs ?? [])
        {
            if (!string.IsNullOrEmpty(a))
            {
                parts.Add(Q(a));
            }
        }

        var body = string.Join('\n', Template);
        body = body.Replace("__SCRUBVARS__",
            string.Join(',', ChildVars.Select(v => "'" + v + "'")), StringComparison.Ordinal);
        body = body.Replace("__DIR__", dir.Replace("'", "''", StringComparison.Ordinal), StringComparison.Ordinal);
        body = body.Replace("__TITLE__", title.Replace("'", "''", StringComparison.Ordinal), StringComparison.Ordinal);
        body = body.Replace("__CLAUDELINE__", string.Join(' ', parts), StringComparison.Ordinal);
        return body;
    }

    /// <summary>
    /// The exact bytes the PowerShell would leave on disk: UTF-8 with a BOM, and
    /// the trailing CRLF <c>Set-Content</c> appends.
    /// </summary>
    /// <remarks>
    /// 🔑 COMPARED AS BYTES ON PURPOSE. The body's own newlines are LF and the
    /// terminator is CRLF, and PowerShell 5.1 reads a .ps1 as ANSI unless a BOM
    /// says otherwise - so "the same text" is not the same file, and this script
    /// is one whose mis-parse would be silent.
    /// </remarks>
    public static byte[] FileBytes(
        string dir,
        string? sessionId,
        string title,
        IEnumerable<string>? claudeArgs = null,
        bool remoteControl = true)
    {
        var text = Text(dir, sessionId, title, claudeArgs, remoteControl) + "\r\n";
        return [.. Encoding.UTF8.GetPreamble(), .. new UTF8Encoding(false).GetBytes(text)];
    }

    private static string Q(string v) => "'" + v.Replace("'", "''", StringComparison.Ordinal) + "'";

    private static string Slug(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var c in s)
        {
            sb.Append(char.IsAsciiLetterOrDigit(c) ? c : '-');
        }

        return sb.ToString();
    }

    /// <summary>PowerShell's <c>Split-Path -Leaf</c>, which ignores a trailing separator.</summary>
    private static string Leaf(string dir)
    {
        var t = dir.TrimEnd('\\', '/');
        if (t.Length == 0)
        {
            return dir;
        }

        var i = t.LastIndexOfAny(['\\', '/']);
        return i < 0 ? t : t[(i + 1)..];
    }
}
